### ISSUE TITLE
Project doesn't compile

### ISSUE THREAD

**Issue by sheldon-white** [renesca/renesca-example#2]
Following the instructions (using scala 2.11.7 0r 2.11.8)

**garnet:/Users/swhite/projects/renesca-example> sbt run
[info] Loading global plugins from /Users/swhite/.sbt/0.13/plugins
[info] Loading project definition from /Users/swhite/projects/renesca-example/project
[info] Set current project to renesca-example (in build file:/Users/swhite/projects/renesca-example/)
[info] Updating {file:/Users/swhite/projects/renesca-example/}renesca-example...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /Users/swhite/projects/renesca-example/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.8. Compiling...
[info]   Compilation completed in 13.987 s
[error] /Users/swhite/projects/renesca-example/src/main/scala/renesca/example/Schema.scala:11: type mismatch;
[error]  found   : scala.collection.mutable.Buffer[renesca.example.Food]
[error]  required: Set[renesca.example.Food]
[error]     filter(_.labels.contains(Food.label)).map(Food.wrap)
[error]                                              ^
[error] /Users/swhite/projects/renesca-example/src/main/scala/renesca/example/Schema.scala:29: type mismatch;
[error]  found   : scala.collection.mutable.Buffer[renesca.example.Animal]
[error]  required: Set[renesca.example.Animal]
[error]     filter(_.labels.contains(Animal.label)).map(Animal.wrap)
[error]                                                ^
[error] two errors found
[error](compile:compileIncremental) Compilation failed
[error] Total time: 18 s, completed May 26, 2016 6:43:50 PM
garnet:/Users/swhite/projects/renesca-example>**

**Comment by sheldon-white** [comment]
Here's the fixed code.

package renesca.example

import renesca.graph._
import renesca.parameter._
import renesca.parameter.implicits._

case class Animal(node: Node) {
  val label = Label("ANIMAL")
  def eats(implicit graph: Graph): Set[Food] = node.outRelations.
    filter(_.relationType == Eats.relationType).map(_.endNode).
    filter(_.labels.contains(Food.label)).map(Food.wrap).toSet
  def name: String = node.properties("name").asInstanceOf[StringPropertyValue]
}

object Animal {
  val label = Label("ANIMAL")
  def wrap(node: Node) = new Animal(node)
  def create(name: String): Animal = {
    val wrapped = wrap(Node.create(List(label)))
    wrapped.node.properties.update("name", name)
    wrapped
  }
}

case class Food(node: Node) {
  val label = Label("FOOD")
  def rev_eats(implicit graph: Graph): Set[Animal] = node.inRelations.
    filter(_.relationType == Eats.relationType).map(_.startNode).
    filter(_.labels.contains(Animal.label)).map(Animal.wrap).toSet
  def name: String = node.properties("name").asInstanceOf[StringPropertyValue]
  def amount: Long = node.properties("amount").asInstanceOf[LongPropertyValue]
  def `amount_=`(newValue: Long) { node.properties.update("amount", newValue) }
}

object Food {
  val label = Label("FOOD")
  def wrap(node: Node) = new Food(node)
  def create(amount: Long, name: String): Food = {
    val wrapped = wrap(Node.create(List(label)))
    wrapped.node.properties.update("amount", amount)
    wrapped.node.properties.update("name", name)
    wrapped
  }
}

case class Eats(startNode: Animal, relation: Relation, endNode: Food)

object Eats {
  val relationType = RelationType("EATS")
  def wrap(relation: Relation) = {
    Eats(Animal.wrap(relation.startNode), relation, Food.wrap(relation.endNode))
  }
  def create(startNode: Animal, endNode: Food): Eats = {
    wrap(Relation.create(startNode.node, relationType, endNode.node))
  }
}

**Comment by cornerman** [comment]
Thank you for the bug report and the proposed fix.
